### ISSUE TITLE
chore: rsync not working under windows

### ISSUE THREAD

**Issue by valentingavran** [valentingavran/anglify#136]
### Feature Description

There is a prebuild step in the build command which generates the documentation. Unfortunately this command does not work under windows, because rsync does not exist there.

Therefore, this should be adapted so that developers who use a Windows PC can also execute the command

**Comment by iCrawl** [comment]
Tip: Don't use windows.

**Comment by valentingavran** [comment]
Unfortunately, we can't influence that and in order to make Anglify accessible and welcome for everyone, we have to adapt that. This will also allow a lot more people to collaborate on Anglify

**Comment by iCrawl** [comment]
Joking, joking.

I have great experience with using https://github.com/sindresorhus/cpy-cli for this.
