### ISSUE TITLE
bug(FormField): Outline form with label display issue

### ISSUE THREAD

**Issue by nezhar** [valentingavran/anglify#137]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

0.14.0

### Reproduction

Steps to reproduce:
1. Create a form input with outline and label:
```
<anglify-form-field type="outlined" label="Outlined">
  <input anglifyInput />
</anglify-form-field>
``` 
2. Add some text to the form

![image](https://user-images.githubusercontent.com/4420927/168328139-a149720b-22c2-4a6b-aa13-20c1bad8d9a1.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/4420927/168328184-5ee2a4f0-9220-45f5-b3d0-bedc933419c8.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/4420927/168328231-fe7a3d30-712c-49d8-818b-dc578898b063.png)

### Environment

- Angular: 13.3.8
- Anglify: 0.17.2
- Browser(s): Google Chrome (Version 101.0.4951.54)
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by valentingavran** [comment]
Thanks for opening this ticket. Until the problem is fixed, you can use the label slot instead of the label attribute. This way the bug will not occur.

```html

<anglify-form-field type="outlined">
  <ng-template slot="label">Username</ng-template>
  <input anglifyInput />
</anglify-form-field>
```
