### ISSUE TITLE
chore: add a11y linting rules

### ISSUE THREAD

**Issue by valentingavran** [valentingavran/anglify#141]
### Feature Description

- "@angular-eslint/template/accessibility-alt-text": 2,
- "@angular-eslint/template/accessibility-elements-content": 2,
- "@angular-eslint/template/accessibility-label-for": 2,
- "@angular-eslint/template/no-positive-tabindex":  2,
- "@angular-eslint/template/accessibility-table-scope": 2,
- "@angular-eslint/template/accessibility-valid-aria": 2,
- "@angular-eslint/template/click-events-have-key-events": 2,
- "@angular-eslint/template/mouse-events-have-key-events": 2,
- "@angular-eslint/template/no-autofocus": 2,
- "@angular-eslint/template/no-distracting-elements": 2

### Use Case

Ensures a few simple a11y rules

**Comment by iCrawl** [comment]
This is already done with the `eslint-config-neon` switch 👍 

https://github.com/iCrawl/eslint-config-neon/blob/main/src/angular.js#L44-L66
