### ISSUE TITLE
feat(Snackbar): Simple opening method

### ISSUE THREAD

**Issue by valentingavran** [valentingavran/anglify#170]
### Feature Description

To open a Snackbar, you currently have to call the open method first and then you have to subscribe to the returned observable of this method. So far so good, as there are certainly scenarios where one might need such an observable.

However, in many cases this is not necessary, as Snackbars are opened only as a side effect. Also, when I first used it, I didn't think at all that it was an observable. I wondered why the following code

```typescript
public constructor(public readonly snackbarService: SnackbarService) {
    this.snackbarService.open({data: { label: "Hello world" }});
}
```
 did nothing at all.

### Suggestion

1. The current `open()` method of the `SnackbarService` should be renamed to `open$(...)` and work as before.
2. Then a new `open()` method should be created which internally creates a subscription to the observable of the previously renamed `open$()` method.

In this way, an abstraction layer is created and little new code needs to be written.

**Comment by iCrawl** [comment]
Can you cover ideas where you return data or want to know what/how the modal was closed; how that would work/look like?

Since currently you can do:

```ts
public constructor(public readonly snackbarService: SnackbarService) {
    this.snackbarService.open({ data: { label: "Hello world" } }).subscribe({
      complete: () => {
        console.log('snackbar: closed');
      },
      next: data => {
        console.log('snackbar: data:', data);
      },
    });
}
```

Where data in `next` would be `'internal.timeout'` or the custom message you pass via `{ data: { actions: { id: 'custom.reason' } } }` or `'internal.dismissed'` if no `id` is passed and only `label` in the `actions` object.

**Comment by valentingavran** [comment]
I have now thought about it a little bit longer. I think the current solution is not perfect, however it is the best possible solution in javascript.

The only problem I have is the naming, as it turns out. The name of the method `open()` makes you think that it already opens the Snackbar.  The `.subscribe()`afterwards makes you think that you only need that, to perform side effects.
I would love it, if the name of the method could stay the same and if we could add the subscribe optionally at the end, so that we can react to side effects. But I think that is not possible.

Maybe it would be enough if we just rename the open method. Here are a few name suggestions:

- `this.snackbarService.build({...}).subscribe();`
- `this.snackbarService.buildSnackbar({...}).subscribe();`
- `this.snackbarService.createConfiguration({...}).subscribe();`
- `this.snackbarService.configureNewSnackbar({...}).subscribe();`

I hope I have been able to better describe what is causing confusion.

**Comment by valentingavran** [comment]
Or we can completely omit returning an observable and pass the next and complete functions as parameters, the same way Angular Material does it

**Comment by iCrawl** [comment]
I don't think doing some sort of callback pattern or passing functions is the way to go here. Observables are a lot more flexible.
