### ISSUE TITLE
bug(Navigation Drawer): ngModel directive conflict when using Angular FormsModule

### ISSUE THREAD

**Issue by svengraziani** [valentingavran/anglify#202]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Reproduction

Steps to reproduce:
1.  ensure your application has FormsModule from angular imported
2. make use of [ngModel] property of anglify-navigation-drawer (this activates the directive: ngModel)

https://stackblitz.com/edit/angular-ivy-lmu9ea?file=src/app/app.module.ts

### Expected Behavior

No Error on Console

### Actual Behavior

Error on Console: "Error: No value accessor for form control with unspecified name attribute".
When providing a name attribute to the navigation drawer the Console output is: "No value accessor for form control with name: 'name used in the name attribute'"

### Environment

- Angular: 14.0
- Anglify: 0.27.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by valentingavran** [comment]
Should now be fixed with version v0.28.0
