### ISSUE TITLE
Select Component

### ISSUE THREAD

**Issue by valentingavran** [valentingavran/anglify#26]
It would be best if we had a menu component/directive that is used by the Select component. Then also context menus, icon menus etc. can be implemented without problems.

Here is the material design specification of Menus: https://material.io/components/menus#dropdown-menu
The Dropdown Menu section on this page mainly describes selects. The rest of the page is about menus in general.

**Comment by iCrawl** [comment]
Needs feature parity of: https://github.com/ng-select/ng-select
