### ISSUE TITLE
Offset for menus and tooltips should not be set on the sides

### ISSUE THREAD

**Issue by valentingavran** [valentingavran/anglify#82]
Offsets of positionable components describe the distance to the host component. However, the same value is used for the distance to the browser border and that is not good.

If the offset is set to a value greater than the default value (which looks good out of the box), then the distance to the host component changes as expected. But at the same time the distance to the screen border also increases by the same value.

**Comment by iCrawl** [comment]
This should be solved with #112 and if any other side-effects occur where this could cause issues, I would put this under "user fault".
